apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:                 # specfication for deploymnet
  replical: 1
  selector:
    matchLabels:
      app: nginx
  templete:
    metadata:
      labels:
        app: nginx
    spec:         # specfication for Pod
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort:80
